version: "3.1"

recipe: default.v1

language: zh

pipeline:
- name: JiebaTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 50
  intent_classification: true
  entity_recognition: true
  constrain_similarities: true
  model_confidence: softmax
  sparsity_loss_weight: 1e-3
  regularization_constant: 0.001
  connection_density: 0.2
  evaluate_every_number_of_epochs: 10
  evaluate_on_number_of_examples: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 50
  constrain_similarities: true
  model_confidence: softmax
- name: FallbackClassifier
  threshold: 0.4

policies:
- name: MemoizationPolicy
  max_history: 5
- name: RulePolicy
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 50
  constrain_similarities: true
  model_confidence: softmax
- name: TEDPolicy
  max_history: 5
  epochs: 50
  constrain_similarities: true
  model_confidence: softmax
  max_training_history: 5
  use_gpu: false

assistant_id: 20251203-232745-amicable-lumber
